### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/reporting-engine#21]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] google_cloud_print
- [ ] report_extended
- [ ] report_extended_account
- [ ] report_extended_payment_group
- [ ] report_extended_purchase
- [ ] report_extended_sale
- [ ] report_extended_stock
- [ ] report_extended_website_portal_sale
