### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/reporting-engine#54]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [ ] report_extended_website_sale
- [ ] report_extended_account
- [ ] report_extended_stock
- [ ] report_extended_payment_group
- [ ] base_report_to_printer_aeroo
- [ ] report_extended_purchase
- [ ] report_extended_sale
- [ ] google_cloud_print
- [ ] report_extended
